import React from 'react';
import { AlertTriangle, X } from 'lucide-react';
import { SlideUpModal } from './SlideUpModal';
import { haptics } from '../utils/haptics';

interface MinorAIDisclaimerProps {
    isOpen: boolean;
    onAccept: () => void;
    onDecline: () => void;
    isDarkMode: boolean;
}

export const MinorAIDisclaimer: React.FC<MinorAIDisclaimerProps> = ({
    isOpen,
    onAccept,
    onDecline,
    isDarkMode
}) => {
    const handleAccept = () => {
        haptics.success();
        onAccept();
    };

    const handleDecline = () => {
        haptics.selection();
        onDecline();
    };

    return (
        <SlideUpModal isOpen={isOpen} onClose={onDecline} isDarkMode={isDarkMode}>
            <div className="p-6">
                {/* Header */}
                <div className="flex items-center justify-between mb-6">
                    <div className="flex items-center gap-3">
                        <div className="p-3 rounded-full bg-amber-500/20">
                            <AlertTriangle className="text-amber-500" size={24} />
                        </div>
                        <div>
                            <h2 className={`text-2xl font-display font-bold ${isDarkMode ? 'text-white' : 'text-warm-gray-green'}`}>
                                AI Features - Important Notice
                            </h2>
                            <p className={`text-sm ${isDarkMode ? 'text-white/60' : 'text-warm-gray-green/60'}`}>
                                Please read carefully
                            </p>
                        </div>
                    </div>
                    <button
                        onClick={handleDecline}
                        className={`p-2 rounded-full transition-colors ${isDarkMode ? 'hover:bg-white/10' : 'hover:bg-sage/10'}`}
                    >
                        <X size={20} className={isDarkMode ? 'text-white/60' : 'text-warm-gray-green/60'} />
                    </button>
                </div>

                {/* Content */}
                <div className={`p-5 rounded-xl mb-6 ${isDarkMode ? 'bg-amber-500/10 border border-amber-500/20' : 'bg-amber-50 border border-amber-200'}`}>
                    <p className={`text-sm mb-4 ${isDarkMode ? 'text-white/90' : 'text-warm-gray-green'}`}>
                        You're about to use AI-generated content. As a young user, it's important to understand:
                    </p>

                    <ul className={`space-y-3 text-sm ${isDarkMode ? 'text-white/80' : 'text-warm-gray-green/80'}`}>
                        <li className="flex items-start gap-2">
                            <span className="text-amber-500 font-bold mt-0.5">•</span>
                            <span><strong>AI can make mistakes</strong> - The content is generated by artificial intelligence and may not always be accurate or appropriate.</span>
                        </li>
                        <li className="flex items-start gap-2">
                            <span className="text-amber-500 font-bold mt-0.5">•</span>
                            <span><strong>Always verify important information</strong> - Don't rely solely on AI for important decisions or advice.</span>
                        </li>
                        <li className="flex items-start gap-2">
                            <span className="text-amber-500 font-bold mt-0.5">•</span>
                            <span><strong>Talk to a trusted adult</strong> - If you're unsure about anything, discuss it with a parent, guardian, teacher, or counselor.</span>
                        </li>
                        <li className="flex items-start gap-2">
                            <span className="text-amber-500 font-bold mt-0.5">•</span>
                            <span><strong>This is not professional advice</strong> - AI content is for motivational purposes only, not medical, legal, or professional guidance.</span>
                        </li>
                        <li className="flex items-start gap-2">
                            <span className="text-amber-500 font-bold mt-0.5">•</span>
                            <span><strong>Use responsibly</strong> - AI is a tool to support your growth, but your judgment and real-world guidance matter most.</span>
                        </li>
                    </ul>
                </div>

                {/* Parental Note */}
                <div className={`p-4 rounded-lg mb-6 ${isDarkMode ? 'bg-white/5' : 'bg-sage/5'}`}>
                    <p className={`text-xs ${isDarkMode ? 'text-white/60' : 'text-warm-gray-green/60'}`}>
                        <strong>Note for Parents/Guardians:</strong> We encourage you to discuss AI usage with your teen.
                        AI features can be disabled in Settings at any time.
                    </p>
                </div>

                {/* Actions */}
                <div className="flex flex-col gap-3">
                    <button
                        onClick={handleAccept}
                        className={`w-full py-3 rounded-xl font-bold transition-all hover:scale-[1.02] active:scale-95 ${isDarkMode
                                ? 'bg-pale-gold text-warm-gray-green'
                                : 'bg-sage text-white'
                            }`}
                    >
                        I Understand & Accept
                    </button>
                    <button
                        onClick={handleDecline}
                        className={`w-full py-3 rounded-xl font-medium transition-colors ${isDarkMode
                                ? 'bg-white/5 hover:bg-white/10 text-white/80'
                                : 'bg-sage/5 hover:bg-sage/10 text-sage'
                            }`}
                    >
                        No Thanks, Disable AI
                    </button>
                </div>
            </div>
        </SlideUpModal>
    );
};
