import { useState } from 'react';
import { motion } from 'framer-motion';
import { Check, X } from 'lucide-react';
import { useSubscription } from '../contexts/SubscriptionContext';

// ─── Feature list ─────────────────────────────────────────────────────────────
// Written as outcomes the user lives, not features the app has.

export const FEATURES = [
    'Morning practice — intention, gratitude, a message written just for today',
    'An AI that remembers what you said yesterday and uses it tomorrow',
    'Evening reflection to close every day with honesty',
    'Your Mandala of Growth, built ring by ring with every practice',
    'Partner chat for the moments between practices',
    'Weekly story of your growth, written in your own words',
];

// AI disclosure text — surfaced in the UI per Apple guidelines (AI-generated content must be disclosed)
export const AI_DISCLOSURE = 'Affirmations, coaching messages, and reflections are generated by AI, personalized to your entries.';

// Fine print subscription terms
export const SUBSCRIPTION_TERMS = 'Billed through Apple. Subscription renews automatically. Cancel anytime.';

// ─── Ghost mandala SVG ─────────────────────────────────────────────────────────
// Shows 4 concentric rings — filled rings for returning users, ghost for new.

const GhostMandala: React.FC<{ filledRings?: number }> = ({ filledRings = 0 }) => {
    const cx = 56;
    const cy = 56;
    const radii = [10, 20, 30, 40, 50];

    return (
        <svg viewBox="0 0 112 112" width="100" height="100" style={{ overflow: 'visible' }}>
            <defs>
                <radialGradient id="pwGlow" cx="50%" cy="50%" r="50%">
                    <stop offset="0%" stopColor="#C96A3A" stopOpacity="0.85" />
                    <stop offset="100%" stopColor="#C96A3A" stopOpacity="0" />
                </radialGradient>
            </defs>

            {/* Ghost rings */}
            {[0, 1, 2, 3].map(i => (
                <circle
                    key={`ghost-${i}`}
                    cx={cx} cy={cy}
                    r={radii[i + 1]}
                    fill="none"
                    stroke={i < filledRings ? 'rgba(201,106,58,0.55)' : 'rgba(255,255,255,0.07)'}
                    strokeWidth="8"
                />
            ))}

            {/* Newest filled ring gets the accent */}
            {filledRings > 0 && (
                <circle
                    cx={cx} cy={cy}
                    r={radii[filledRings]}
                    fill="none"
                    stroke="#C96A3A"
                    strokeWidth="8"
                    opacity={0.85}
                />
            )}

            {/* Center seed */}
            <circle cx={cx} cy={cy} r={radii[0]} fill="url(#pwGlow)" />
            <circle cx={cx} cy={cy} r={4} fill="#C96A3A" opacity={0.9} />
        </svg>
    );
};

// ─── Props ────────────────────────────────────────────────────────────────────

interface PaywallScreenProps {
    onDismiss?: () => void;
    onShowPrivacy?: () => void;
    onShowTerms?: () => void;
    firstName?: string;
    practiceCount?: number;
    gratitudeCount?: number;
}

// ─── Component ────────────────────────────────────────────────────────────────

export function PaywallScreen({ onDismiss, onShowPrivacy, onShowTerms, firstName, practiceCount = 0, gratitudeCount = 0 }: PaywallScreenProps) {
    const { purchaseMonthly, purchaseAnnual, restorePurchases, prices } = useSubscription();
    const [loading, setLoading] = useState<'monthly' | 'annual' | 'restore' | null>(null);
    const [error, setError] = useState<string | null>(null);

    const isReturning = practiceCount > 0;

    // Rings filled based on practice milestones (mirrors ring ceremony thresholds)
    const filledRings = practiceCount >= 90 ? 4
        : practiceCount >= 55 ? 3
        : practiceCount >= 28 ? 2
        : practiceCount >= 10 ? 1
        : 0;

    const handle = async (type: 'monthly' | 'annual') => {
        setError(null);
        setLoading(type);
        const result = type === 'annual' ? await purchaseAnnual() : await purchaseMonthly();
        setLoading(null);
        if (result.error) setError(result.error);
    };

    const handleRestore = async () => {
        setError(null);
        setLoading('restore');
        const result = await restorePurchases();
        setLoading(null);
        if (result.error) setError(result.error);
    };

    // ── Copy engine ────────────────────────────────────────────────────────────

    const headline = isReturning
        ? (firstName ? `${firstName}, keep going.` : 'Keep going.')
        : 'You started.\nKeep going — free for 7 days.';

    const subhead = isReturning
        ? 'Your practice is already taking root. Subscribe to keep building on what you started.'
        : 'That was your first morning practice. Your Palante Partner already knows your intention. Come back tonight and it will remember.';

    const annualBadge = isReturning
        ? 'Pick up where you left off · 50% off monthly'
        : 'Most popular · 50% off monthly';

    // Localized store prices — USD copy is the fallback until offerings load
    const annualPrice = prices.annual ?? '$59.99';
    const monthlyPrice = prices.monthly ?? '$9.99';
    const annualPerMonth = prices.annualPerMonth ?? '$4.99';

    const annualSubline = isReturning ? `Just ${annualPerMonth} a month, billed annually` : `Just ${annualPerMonth} a month · 7 days free`;
    const monthlySubline = isReturning ? 'Cancel anytime' : '7 days free · cancel anytime';
    const finePrint = isReturning
        ? 'Billed through Apple. Subscription renews automatically. Cancel anytime.'
        : 'Cancel anytime before day 7 — no charge, no hassle.\nBilled through Apple. Subscription renews automatically.';

    // ── Render ─────────────────────────────────────────────────────────────────

    return (
        <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 flex flex-col"
            style={{ background: 'linear-gradient(160deg, #4a6741 0%, #3a5438 50%, #2d4a2e 100%)' }}
        >
            {/* Grain overlay */}
            <svg className="absolute inset-0 w-full h-full opacity-[0.04] pointer-events-none" aria-hidden>
                <filter id="pwGrain">
                    <feTurbulence type="fractalNoise" baseFrequency="0.65" numOctaves="3" stitchTiles="stitch" />
                </filter>
                <rect width="100%" height="100%" filter="url(#pwGrain)" />
            </svg>

            {/* Terracotta glow behind the mandala */}
            <div
                className="absolute pointer-events-none"
                style={{
                    top: 40, left: '50%', transform: 'translateX(-50%)',
                    width: 240, height: 240,
                    background: 'radial-gradient(circle, rgba(201,106,58,0.12) 0%, transparent 70%)',
                }}
            />

            {onDismiss && (
                <button
                    onClick={onDismiss}
                    className="absolute top-12 right-5 z-10 p-2 rounded-full"
                    style={{ background: 'rgba(255,255,255,0.08)' }}
                    aria-label="Close"
                >
                    <X size={18} color="#FAF7F3" />
                </button>
            )}

            <div className="flex-1 overflow-y-auto px-6 pt-14 pb-10">

                {/* Mandala */}
                <motion.div
                    initial={{ opacity: 0, scale: 0.7 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.9, ease: [0.25, 0.46, 0.45, 0.94] }}
                    className="flex justify-center mb-7"
                >
                    <GhostMandala filledRings={filledRings} />
                </motion.div>

                {/* Returning user stat callout */}
                {isReturning && (
                    <motion.div
                        initial={{ opacity: 0, y: 6 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: 0.15, duration: 0.5 }}
                        className="flex justify-center gap-4 mb-5"
                    >
                        {[
                            { value: practiceCount, label: 'practices' },
                            { value: gratitudeCount, label: 'gratitudes written' },
                        ].map(({ value, label }) => (
                            <div
                                key={label}
                                className="flex flex-col items-center px-5 py-2 rounded-xl"
                                style={{ background: 'rgba(201,106,58,0.1)', border: '1px solid rgba(201,106,58,0.2)' }}
                            >
                                <span style={{ fontFamily: 'Poppins, sans-serif', fontWeight: 700, color: '#C96A3A', fontSize: '20px', lineHeight: 1.1 }}>
                                    {value}
                                </span>
                                <span style={{ fontFamily: 'Inter, sans-serif', fontWeight: 400, color: 'rgba(250,247,243,0.5)', fontSize: '11px', marginTop: 2 }}>
                                    {label}
                                </span>
                            </div>
                        ))}
                    </motion.div>
                )}

                {/* Header */}
                <motion.div
                    initial={{ y: 16, opacity: 0 }}
                    animate={{ y: 0, opacity: 1 }}
                    transition={{ delay: 0.2, duration: 0.5 }}
                    className="text-center mb-7"
                >
                    <h1
                        className="mb-3"
                        style={{
                            fontFamily: 'Poppins, sans-serif',
                            fontWeight: 700,
                            color: '#FAF7F3',
                            fontSize: headline.includes('\n') ? '28px' : '30px',
                            letterSpacing: '-0.02em',
                            lineHeight: 1.2,
                            whiteSpace: 'pre-line',
                        }}
                    >
                        {headline}
                    </h1>
                    <p style={{ fontFamily: 'Inter, sans-serif', fontWeight: 400, color: 'rgba(250,247,243,0.58)', fontSize: '14px', lineHeight: 1.55 }}>
                        {subhead}
                    </p>
                </motion.div>

                {/* Features */}
                <motion.div
                    initial={{ y: 16, opacity: 0 }}
                    animate={{ y: 0, opacity: 1 }}
                    transition={{ delay: 0.3, duration: 0.5 }}
                    className="rounded-2xl p-5 mb-6"
                    style={{ background: 'rgba(250,247,243,0.05)', border: '1px solid rgba(229,214,167,0.15)' }}
                >
                    <p style={{ fontFamily: 'Inter, sans-serif', fontWeight: 600, color: 'rgba(229,214,167,0.7)', fontSize: '10px', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: 14 }}>
                        Everything included
                    </p>
                    <ul className="space-y-3">
                        {FEATURES.map((f) => (
                            <li key={f} className="flex items-start gap-3">
                                <Check size={14} color="#C96A3A" strokeWidth={2.5} style={{ flexShrink: 0, marginTop: 2 }} />
                                <span style={{ fontFamily: 'Inter, sans-serif', fontWeight: 400, color: 'rgba(250,247,243,0.82)', fontSize: '13.5px', lineHeight: 1.45 }}>
                                    {f}
                                </span>
                            </li>
                        ))}
                    </ul>
                    <p style={{ fontFamily: 'Inter, sans-serif', fontWeight: 400, color: 'rgba(250,247,243,0.35)', fontSize: '11px', lineHeight: 1.5, marginTop: 14, borderTop: '1px solid rgba(250,247,243,0.08)', paddingTop: 12 }}>
                        {AI_DISCLOSURE}
                    </p>
                </motion.div>

                {/* Annual CTA — primary */}
                <motion.div
                    initial={{ y: 16, opacity: 0 }}
                    animate={{ y: 0, opacity: 1 }}
                    transition={{ delay: 0.38, duration: 0.5 }}
                    className="mb-3"
                >
                    <div className="flex justify-center mb-2">
                        <span
                            className="px-3 py-1 rounded-full"
                            style={{
                                fontFamily: 'Inter, sans-serif', fontWeight: 600,
                                color: '#C96A3A', fontSize: '11px', letterSpacing: '0.07em',
                                textTransform: 'uppercase',
                                background: 'rgba(201,106,58,0.12)',
                                border: '1px solid rgba(201,106,58,0.28)',
                            }}
                        >
                            {annualBadge}
                        </span>
                    </div>
                    <button
                        onClick={() => handle('annual')}
                        disabled={loading !== null}
                        className="w-full rounded-2xl py-4 px-6 flex items-center justify-between transition-opacity active:scale-[0.98]"
                        style={{
                            background: loading === 'annual' ? 'rgba(201,106,58,0.7)' : '#C96A3A',
                            opacity: loading !== null && loading !== 'annual' ? 0.45 : 1,
                        }}
                    >
                        <div className="text-left">
                            <div style={{ fontFamily: 'Poppins, sans-serif', fontWeight: 700, color: '#FAF7F3', fontSize: '17px' }}>
                                {loading === 'annual' ? 'Just a moment…' : `Annual — ${annualPrice} / year`}
                            </div>
                            <div style={{ fontFamily: 'Inter, sans-serif', fontWeight: 400, color: 'rgba(250,247,243,0.78)', fontSize: '13px', marginTop: 2 }}>
                                {annualSubline}
                            </div>
                        </div>
                        {!isReturning && (
                            <div className="rounded-xl px-3 py-1" style={{ background: 'rgba(0,0,0,0.18)' }}>
                                <span style={{ fontFamily: 'Inter, sans-serif', fontWeight: 600, color: '#FAF7F3', fontSize: '12px' }}>
                                    7 days free
                                </span>
                            </div>
                        )}
                    </button>
                </motion.div>

                {/* Monthly CTA — secondary */}
                <motion.div
                    initial={{ y: 16, opacity: 0 }}
                    animate={{ y: 0, opacity: 1 }}
                    transition={{ delay: 0.44, duration: 0.5 }}
                    className="mb-6"
                >
                    <button
                        onClick={() => handle('monthly')}
                        disabled={loading !== null}
                        className="w-full rounded-2xl py-4 px-6 flex items-center justify-between transition-opacity active:scale-[0.98]"
                        style={{
                            background: 'transparent',
                            border: '1.5px solid rgba(250,247,243,0.14)',
                            opacity: loading !== null && loading !== 'monthly' ? 0.45 : 1,
                        }}
                    >
                        <div className="text-left">
                            <div style={{ fontFamily: 'Poppins, sans-serif', fontWeight: 600, color: '#FAF7F3', fontSize: '17px' }}>
                                {loading === 'monthly' ? 'Just a moment…' : `Monthly — ${monthlyPrice} / month`}
                            </div>
                            <div style={{ fontFamily: 'Inter, sans-serif', fontWeight: 400, color: 'rgba(250,247,243,0.5)', fontSize: '13px', marginTop: 2 }}>
                                {monthlySubline}
                            </div>
                        </div>
                    </button>
                </motion.div>

                {error && (
                    <motion.p
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        className="text-center mb-4"
                        style={{ fontFamily: 'Inter, sans-serif', color: '#E57373', fontSize: '13px' }}
                    >
                        {error}
                    </motion.p>
                )}

                {/* Fine print */}
                <div className="text-center space-y-3">
                    <p style={{
                        fontFamily: 'Inter, sans-serif', fontWeight: 400,
                        color: 'rgba(250,247,243,0.35)', fontSize: '12px',
                        lineHeight: 1.55, whiteSpace: 'pre-line',
                    }}>
                        {finePrint}
                    </p>
                    <button
                        onClick={handleRestore}
                        disabled={loading !== null}
                        style={{
                            fontFamily: 'Inter, sans-serif', fontWeight: 500,
                            color: 'rgba(250,247,243,0.38)', fontSize: '13px',
                            background: 'none', border: 'none', cursor: 'pointer',
                        }}
                    >
                        {loading === 'restore' ? 'Restoring…' : 'Restore purchases'}
                    </button>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 16 }}>
                        <button
                            onClick={() => onShowPrivacy?.()}
                            style={{
                                fontFamily: 'Inter, sans-serif', fontWeight: 500,
                                color: 'rgba(250,247,243,0.38)', fontSize: '12px',
                                background: 'none', border: 'none', cursor: 'pointer',
                                textDecoration: 'underline',
                            }}
                        >
                            Privacy Policy
                        </button>
                        <span style={{ color: 'rgba(250,247,243,0.2)', fontSize: '12px' }}>·</span>
                        <button
                            onClick={() => (onShowTerms ?? onShowPrivacy)?.()}
                            style={{
                                fontFamily: 'Inter, sans-serif', fontWeight: 500,
                                color: 'rgba(250,247,243,0.38)', fontSize: '12px',
                                background: 'none', border: 'none', cursor: 'pointer',
                                textDecoration: 'underline',
                            }}
                        >
                            Terms of Use
                        </button>
                    </div>
                </div>

            </div>
        </motion.div>
    );
}
