/**
 * AI disclosure: the plain-language version of what §2 and §12 of the legal terms say.
 *
 * Shown once on first launch (after the age gate, before the app opens) and available
 * any time from Settings. The legal document is the binding text; this is the version
 * a person will actually read, so it has to be accurate rather than merely defensible.
 *
 * Rules for editing this copy:
 *   - Name every provider that receives user text. Right now that is Anthropic (all
 *     written content) and OpenAI (voice synthesis, only when the user taps to listen).
 *   - Say what is actually sent. "Relevant context" is not an honest description of
 *     sending someone's gratitudes and reflections verbatim.
 *   - Any change to what we send, who receives it, or what they may do with it is a
 *     material change: bump AI_DISCLOSURE_VERSION so every existing user sees it again.
 */

import { STORAGE_KEYS } from '../constants/storageKeys';

export const AI_DISCLOSURE_VERSION = '2026-07-25';

export interface AIDisclosureSection {
    heading: string;
    body: string;
}

export const AI_DISCLOSURE: { title: string; intro: string; sections: AIDisclosureSection[] } = {
    title: 'How Palante uses AI',

    intro: 'Your partner is powered by AI. Here is exactly what that means, in plain terms, before you start.',

    sections: [
        {
            heading: 'What the AI writes',
            body: 'Your partner\'s replies, your morning and evening messages, your weekly reflection and letter, and the insights you see over time are all generated by AI. The daily lines you read, the science facts, and the practice itself are written by us and are not generated. Palante does not publish anyone else\'s words, so nothing here is a quotation from another author.',
        },
        {
            heading: 'What we send, and to whom',
            body: 'To write those things, we send what you wrote (your gratitudes, intentions, reflections, and messages to your partner) along with your name and the profile details you gave us, to Anthropic, the company that makes the model. If you tap to hear a message read aloud, that message\'s text is also sent to OpenAI to turn it into speech.',
        },
        {
            heading: 'What happens to it there',
            body: 'It is used to produce your response and nothing else. It is not used to train AI models, it is not sold, and it is never used for advertising. Your entries stay in your account so you can look back on them, and you can export or delete everything from Settings.',
        },
        {
            heading: 'It can be wrong',
            body: 'AI writes things that sound confident and are not true. Your partner is not a therapist, a doctor, or a crisis service, and nothing it says is professional advice. Trust yourself over it, and reach out to a real person when it matters.',
        },
        {
            heading: 'You can turn it off',
            body: 'Palante works without AI. Turn it off and nothing you write is sent anywhere. You get written messages and prompts instead of generated ones, and everything else in the app works the same. You can change this any time in Settings.',
        },
    ],
};

/** Shape of the acknowledgment written to storage. */
export interface AIDisclosureAcknowledgment {
    acknowledged: boolean;
    timestamp: string;
    version: string;
}

/**
 * True when this user has already acknowledged the current version of the disclosure.
 * A stored acknowledgment of an older version does not count. That is the whole point
 * of versioning it.
 */
export const hasAcknowledgedAIDisclosure = (): boolean => {
    try {
        const raw = localStorage.getItem(STORAGE_KEYS.AI_DISCLOSURE_ACKNOWLEDGED);
        if (!raw) return false;
        const parsed = JSON.parse(raw) as Partial<AIDisclosureAcknowledgment>;
        return parsed.acknowledged === true && parsed.version === AI_DISCLOSURE_VERSION;
    } catch {
        // Unreadable record: show the disclosure again rather than assume consent.
        return false;
    }
};

export const recordAIDisclosureAcknowledgment = (): void => {
    const record: AIDisclosureAcknowledgment = {
        acknowledged: true,
        timestamp: new Date().toISOString(),
        version: AI_DISCLOSURE_VERSION,
    };
    try {
        localStorage.setItem(STORAGE_KEYS.AI_DISCLOSURE_ACKNOWLEDGED, JSON.stringify(record));
    } catch {
        // Storage full or blocked. The user still made a choice this session; failing to
        // persist means they see the screen again next launch, which is the safe miss.
    }
};
